apiVersion: apps/v1
kind: Deployment
metadata:
  name: grecho
  labels:
    app: grecho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grecho
  template:
    metadata:
      labels:
        app: grecho
    spec:
      containers:
      - name: grecho
        image: ghcr.io/emilzackrisson/grecho:latest
        ports:
        - containerPort: 8001


---

apiVersion: v1
kind: Service
metadata:
  name: grecho
spec:
  selector:
    app.kubernetes.io/name: grecho
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP
