---
apiVersion: v1
kind: Service
metadata:
  name: grecho
  namespace: calico-system
spec:
  selector:
    k8s-app: whisker
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
