apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-tcp-tcpecho-eg
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: tcpecho
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.200.200.0/24
      ports:
        - protocol: TCP
          port: 32000
          endPort: 32768
---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-tcp-grecho-eg
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: grecho
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.200.200.0/24
      ports:
        - protocol: TCP
          port: 32000
          endPort: 32768
