apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-post-root
  namespace: default
spec:
  selector: app == "grecho"
  ingress:
    - action: Allow
      protocol: TCP
      destination:
        ports: [8001]
      http:
        methods: ["POST"]
        paths:
          - exact: /
