apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-http-post
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: grecho
  types:
    - Ingress
  ingress:
    - action: Allow
      http:
        methods: ["POST", "GET"]
        paths:
          - prefix: "/"
